name: Build, Tag, and Release Maven Project

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the `main` branch
    # or use 'pull_request' if you want to create tags on PR merges

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to the project directory
      run: cd duplicate-message-detector-kafka-connect-custom-smt

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('duplicate-message-detector-kafka-connect-custom-smt/**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        cd duplicate-message-detector-kafka-connect-custom-smt
        mvn clean package
    - name: Archive JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-artifact
        path: duplicate-message-detector-kafka-connect-custom-smt/target/*.jar

  create_new_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest tag
      id: get_tag
      run: |
        # Navigate to the directory
        cd duplicate-message-detector-kafka-connect-custom-smt

        # Get the most recent tag in the repo (in the format vX.Y.Z)
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest tag: $latest_tag"

        # If no tags exist, default to v0.0.0
        if [[ -z "$latest_tag" ]]; then
          latest_tag="v0.0.0"
        fi

        # Increment the patch version of the tag (X.Y.Z -> X.Y.(Z+1))
        version_parts=(${latest_tag//./ })
        patch_version=${version_parts[2]}

        # Increment the patch version
        new_patch_version=$((patch_version + 1))
        new_tag="v${version_parts[0]}.${version_parts[1]}.$new_patch_version"

        echo "New tag: $new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create and push new tag
      run: |
        # Navigate to the directory
        cd duplicate-message-detector-kafka-connect-custom-smt

        # Create the new tag
        git tag ${{ env.new_tag }}

        # Push the tag to the remote repository
        git push origin ${{ env.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: create_new_tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: duplicate-message-detector-kafka-connect-custom-smt/target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
